# Generated by Django 3.2.4 on 2022-11-30 17:15

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='USWDSCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='uswds_cards_uswdscard', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(help_text='Max length is 60 characters.', max_length=60)),
                ('text', models.TextField(blank=True, help_text='320 max character for a card description.', max_length=320, null=True)),
                ('card_type', models.CharField(choices=[('card', 'Card'), ('card-media', 'Card with media'), ('card-media-heading-first', 'Card with media heading first'), ('card-media-inset', 'Inset media'), ('card-media-exdent', 'Exdent media')], default='card', max_length=60)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'USWDS Hero',
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='USWDSFlagCardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=255)),
                ('is_external', models.BooleanField(default=False, null=True)),
                ('external_url', models.URLField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('internal', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('uswds_flag_card_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uswds_flag_card_link', to='uswds_cards.uswdscard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='USWDSFlagCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='uswds_cards_uswdsflagcard', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(help_text='Max length is 60 characters.', max_length=60)),
                ('text', models.TextField(blank=True, help_text='320 max character for a card description.', max_length=320, null=True)),
                ('card_type', models.CharField(choices=[('card-flag', 'Default flag'), ('card-flag-right-inset', 'Flag media right inset')], default='card', max_length=60)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'USWDS Hero',
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='USWDSCardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=255)),
                ('is_external', models.BooleanField(default=False, null=True)),
                ('external_url', models.URLField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('internal', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('uswds_card_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uswds_card_link', to='uswds_cards.uswdscard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
