# Generated by Django 3.2.4 on 2022-11-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uswds_cards', '0002_uswdscardgrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uswdsflagcardlink',
            name='uswds_flag_card_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uswds_flag_card_link', to='uswds_cards.uswdsflagcard'),
        ),
    ]
