# Generated by Django 3.2.4 on 2022-11-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uswds_cards', '0003_alter_uswdsflagcardlink_uswds_flag_card_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='uswdscardgrid',
            name='columns',
            field=models.CharField(choices=[('tablet:grid-col-6', 'Two Columns'), ('tablet:grid-col-3', 'Three Columns'), ('tablet:grid-col-4', 'Four Columns')], default='card', max_length=60),
        ),
    ]
