# Generated by Django 3.2.4 on 2022-11-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uswds_cards', '0004_uswdscardgrid_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uswdscardgrid',
            name='columns',
            field=models.CharField(choices=[('tablet:grid-col-6', 'Two Columns'), ('tablet:grid-col-3', 'Three Columns'), ('tablet:grid-col-4', 'Four Columns')], default='tablet:grid-col-3', max_length=60),
        ),
    ]
