# Generated by Django 3.2 on 2022-11-26 17:48

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFooterAgencyModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='uswds_footer_agency_sitefooteragencymodel', serialize=False, to='cms.cmsplugin')),
                ('agency_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_url', models.URLField(blank=True, max_length=255, null=True)),
                ('services_description', models.TextField(blank=True, null=True)),
                ('services_link_title', models.CharField(blank=True, max_length=255, null=True)),
                ('services_link_url', models.URLField(blank=True, null=True)),
                ('agency_logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_logo_site_footer_agency_model', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SiteFooterAgencyMenuLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=255)),
                ('is_external', models.BooleanField(default=False, null=True)),
                ('external_url', models.URLField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('footer_agency_menu_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_agency_menu_link', to='uswds_footer_agency.sitefooteragencymodel')),
                ('internal', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
