# Generated by Django 3.2.4 on 2022-11-30 00:48

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='USWDSCTALink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=255)),
                ('is_external', models.BooleanField(default=False, null=True)),
                ('external_url', models.URLField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('internal', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USWDSCTAText',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='uswds_cta_uswdsctatext', to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='uswds_cta.uswdsctalink')),
                ('style', models.CharField(choices=[('align', 'Aline'), ('stack', 'Stack')], default='align', max_length=60)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
