# Generated by Django 3.2.4 on 2022-11-30 01:30

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('uswds_cta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USWDSCTATextLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=255)),
                ('is_external', models.BooleanField(default=False, null=True)),
                ('external_url', models.URLField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('internal', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='uswdsctatext',
            name='link',
        ),
        migrations.AlterField(
            model_name='uswdsctatext',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='uswds_cta_uswdsctatext', serialize=False, to='cms.cmsplugin'),
        ),
        migrations.DeleteModel(
            name='USWDSCTALink',
        ),
        migrations.AddField(
            model_name='uswdsctatextlink',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uswds_cta_link', to='uswds_cta.uswdsctatext'),
        ),
    ]
