# Generated by Django 3.2.4 on 2022-11-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uswds_cta', '0003_alter_uswdsctatextlink_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uswdsctatextlink',
            old_name='link',
            new_name='uswds_cta_link',
        ),
    ]
