# Generated by Django 3.2.4 on 2022-11-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uswds_cta', '0004_rename_link_uswdsctatextlink_uswds_cta_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uswdsctatext',
            options={'verbose_name': 'USWDS CTA Text'},
        ),
    ]
