# Generated by Django 3.2 on 2022-12-01 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='USWDSGraphicGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='uswds_graphic_list_uswdsgraphicgrid', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Graphic grid',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='USWDSGraphicCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='uswds_graphic_list_uswdsgraphiccard', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(help_text='Max length is 60 characters.', max_length=60)),
                ('text', models.TextField(blank=True, help_text='320 max character for a card description.', max_length=320, null=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Graphic card',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
