# Generated by Django 3.2.4 on 2022-11-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uswds_footer_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitefootersocialmodel',
            options={'verbose_name': 'Site Footer - Agency'},
        ),
    ]
